// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(EmprendimientosContext))]
    partial class EmprendimientosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.ComentarioServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaComentario")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdServicio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdServicio");

                    b.ToTable("ComentarioServicio");
                });

            modelBuilder.Entity("DAL.Models.DetalleServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentService")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdServicio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdServicio")
                        .IsUnique()
                        .HasFilter("[IdServicio] IS NOT NULL");

                    b.ToTable("DetalleServicios");
                });

            modelBuilder.Entity("DAL.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CostoServicio")
                        .HasColumnType("float");

                    b.Property<string>("EstadoServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("IdServicioPublic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdTecnico")
                        .HasColumnType("int");

                    b.Property<string>("TipoServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalServicio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdTecnico");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("DAL.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DAL.Models.ComentarioServicio", b =>
                {
                    b.HasOne("DAL.Models.Servicio", "Servicio")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdServicio");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("DAL.Models.DetalleServicio", b =>
                {
                    b.HasOne("DAL.Models.Servicio", "Servicio")
                        .WithOne("DetalleServicio")
                        .HasForeignKey("DAL.Models.DetalleServicio", "IdServicio");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("DAL.Models.Servicio", b =>
                {
                    b.HasOne("DAL.Models.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Models.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("IdTecnico")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("DAL.Models.Servicio", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("DetalleServicio")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
